Locales['en'] = {
	-- Global
	['custom_kick']  = 'Invoer aangepaste kickbericht',
	['blip_garage']  = 'Garage |Openbaar',
	['blip_garage_private']  = 'Garage |Privaat',
	['blip_pound']  = 'Garage |Pond',
	['loc_garage']  = 'Geparkeerd in garage',
	['loc_pound']  = 'Bij de inbeslagneming',
	['return']  = 'Rendement',
	['store_vehicles']  = 'Bewaar voertuig in de garage.',
	['press_to_enter']  = 'Druk op~Input_pickUp~om het voertuig uit de garage te nemen.',
	['press_to_delete']  = 'Druk op~Input_pickup~om het voertuig in de garage op te slaan.',
	['press_to_impound']  = 'Druk op~Input_pickUp~om toegang te krijgen tot de inbeslagneming.',
	['you_paid']  = 'Je hebt $ betaald',
	['not_enough_money']  = 'Je hebt niet genoeg geld!',
	['return_vehicle']  = 'Winkelvoertuig.',
	['see_mechanic']  = 'Bezoek monteur.',
	['damaged_vehicle']  = 'Voertuig beschadigd!',
	['visit_mechanic']  = 'Bezoek de monteur of repareer jezelf.',
	['cannot_store_vehicle']  = 'Je kunt dit voertuig niet opslaan!',
	['no_vehicle_to_enter']  = 'Er is geen voertuig om in de garage op te slaan.',
	['vehicle_in_garage']  = 'Uw voertuig wordt opgeslagen in de garage.',
	['must_wait']  = 'Je moet wachten~r~%s minuten~w~voordat je weer in beslag hebt gehouden!',
	['get_properties']  = '~y~Private garages!',
	-- Spacers
	['spacer1']  = 'Als het voertuig niet hier is, controleer dan een impiratie !!!',
	['spacer2'] = '---- Aircrafts ----',
	['plate']  = 'Bord',
	['vehicle']  = 'Voertuignaam',
	['location']  = 'Plaats',
	-- Ambulance
	['blip_ambulance_garage']  = 'Garage |Ambulance garage',
	['blip_ambulance_pound']  = 'Garage |Ambulance pond',
	['garage_ambulance']  = 'Ambulance garage',
	['pound_ambulance']  = 'Ambulance pond: fee $%s',
	['garage_no_ambulance']  = 'Je bezit geen ambulancevoertuigen!',
	['garage_no_ambulance_aircraft']  = 'Je bezit geen ambulance-vliegtuigen!',
	['ambulance_is_impounded']  = 'Uw ambulancevoertuig is bij de inbak.',
	-- Police
	['blip_police_garage']  = 'Garage |Politie garage',
	['blip_police_pound']  = 'Garage |Pond',
	['garage_police']  = 'Politie garage',
	['pound_police']  = 'Politie pond: kosten $%s',
	['garage_no_police']  = 'Je hebt geen politie-voertuigen!',
	['garage_no_police_aircraft']  = 'Je hebt geen politie-vliegtuigen!',
	['police_is_impounded']  = 'Je politievoertuig staat bij de inbeslagneming.',
	-- Aircrafts
	['garage_aircrafts']  = 'Vliegtuiggarage',
	['pound_aircrafts']  = 'Vliegtuig pond: kosten $%s',
	['garage_no_aircrafts']  = 'Je bezit geen vliegtuigen!',
	['aircraft_is_impounded']  = 'Je vliegtuig staat bij de inbak.',
	-- Boats
	['garage_boats']  = 'Bootgarage',
	['pound_boats']  = 'Boot pond: kosten $%s',
	['garage_no_boats']  = 'Je hebt geen boten!',
	['boat_is_impounded']  = 'Je boot is bij de inbak.',
	-- Cars
	['garage_cars']  = 'Auto garage',
	['pound_cars']  = 'Auto Pound: Fee $%s',
	['garage_no_cars']  = 'Je hebt geen autos!',
	['car_is_impounded']  = 'Je auto is bij de inbak.',
}